WebApp/Pages/Authors/Create.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Authors
{
    public class CreateModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public CreateModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Author Author { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Authors.Add(Author);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Authors/Delete.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Authors
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public DeleteModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Author Author { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FirstOrDefaultAsync(m => m.Id == id);

            if (author == null)
            {
                return NotFound();
            }
            else
            {
                Author = author;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author != null)
            {
                Author = author;
                _context.Authors.Remove(Author);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Authors/Details.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Authors
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public DetailsModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public Author Author { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }
            else
            {
                Author = author;
            }
            return Page();
        }
    }
}

WebApp/Pages/Authors/Edit.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Authors
{
    public class EditModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public EditModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Author Author { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author =  await _context.Authors.FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }
            Author = author;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Author).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AuthorExists(Author.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AuthorExists(Guid id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }
    }
}

WebApp/Pages/BookAuthors/Create.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Pages.BookAuthors
{
    public class CreateModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public CreateModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "FirstName");
        ViewData["BookId"] = new SelectList(_context.Books, "Id", "Title");
            return Page();
        }

        [BindProperty]
        public BookAuthor BookAuthor { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.BookAuthors.Add(BookAuthor);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/BookAuthors/Delete.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.BookAuthors
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public DeleteModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public BookAuthor BookAuthor { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookauthor = await _context.BookAuthors.FirstOrDefaultAsync(m => m.BookId == id);

            if (bookauthor == null)
            {
                return NotFound();
            }
            else
            {
                BookAuthor = bookauthor;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookauthor = await _context.BookAuthors.FindAsync(id);
            if (bookauthor != null)
            {
                BookAuthor = bookauthor;
                _context.BookAuthors.Remove(BookAuthor);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/BookAuthors/Details.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.BookAuthors
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public DetailsModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public BookAuthor BookAuthor { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookauthor = await _context.BookAuthors.FirstOrDefaultAsync(m => m.BookId == id);
            if (bookauthor == null)
            {
                return NotFound();
            }
            else
            {
                BookAuthor = bookauthor;
            }
            return Page();
        }
    }
}

WebApp/Pages/BookAuthors/Edit.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.BookAuthors
{
    public class EditModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public EditModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public BookAuthor BookAuthor { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? bookId, Guid? authorId)
        {
            if (bookId == null || authorId == null)
            {
                return NotFound();
            }

            var bookauthor =  await _context.BookAuthors.FirstOrDefaultAsync(m => m.BookId == bookId && m.AuthorId == authorId);
            if (bookauthor == null)
            {
                return NotFound();
            }
            BookAuthor = bookauthor;
           ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name");
           ViewData["BookId"] = new SelectList(_context.Books, "Id", "ISBN");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(BookAuthor).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookAuthorExists(BookAuthor.BookId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BookAuthorExists(Guid id)
        {
            return _context.BookAuthors.Any(e => e.BookId == id);
        }
    }
}

WebApp/Pages/BookCategories/Create.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Pages.BookCategories
{
    public class CreateModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public CreateModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["BookId"] = new SelectList(_context.Books, "Id", "Title");
        ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return Page();
        }

        [BindProperty]
        public BookCategory BookCategory { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.BookCategories.Add(BookCategory);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/BookCategories/Delete.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.BookCategories
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public DeleteModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public BookCategory BookCategory { get; set; } = default!;

        [BindProperty (SupportsGet = true)]
        public Guid BookId { get; set; }
        [BindProperty (SupportsGet = true)]
        public Guid CategoryId { get; set; }
        

        public async Task<IActionResult> OnGetAsync()
        {
        
            var bookcategory = await _context.BookCategories.FirstOrDefaultAsync(m => m.BookId == BookId && m.CategoryId == CategoryId);

            if (bookcategory == null)
            {
                return NotFound();
            }
            else
            {
                BookCategory = bookcategory;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
           
            var bookcategory = await _context.BookCategories.Where(bc => bc.BookId == BookId && bc.CategoryId == CategoryId).FirstOrDefaultAsync();
            if (bookcategory != null)
            {
                BookCategory = bookcategory;
                _context.BookCategories.Remove(BookCategory);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Books/Details.cshtml.cs
using Domain;
using Domain.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Books
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public DetailsModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public BookDto BookDto { get; set; } = default!;

        [BindProperty]
        public int ReviewRating { get; set; }

        [BindProperty]
        public string ReviewComment { get; set; } = default!;

        [BindProperty]
        public Guid ReviewId { get; set; } = default!;

        [BindProperty]
        public Guid BookId { get; set; } = default!;

        public async Task<IActionResult> OnPostAddReviewAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            var newReview = new Review
            {
                Rating = ReviewRating,
                Comment = ReviewComment,
                BookId = BookId,
            };

            _context.Reviews.Add(newReview);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Books/Details", new { id = BookId });
        }

        public async Task<IActionResult> OnPostAddReplyAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            var newReply = new Review
            {
                Comment = ReviewComment,
                ParentCommentId = ReviewId,
                BookId = BookId
            };

            _context.Reviews.Add(newReply);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Books/Details", new { id = BookId });
        }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.BookAuthors)!
                .ThenInclude(ba => ba.Author)
                .Include(b => b.Publisher)
                .Include(b => b.BookCategories)!
                .ThenInclude(bc => bc.Category)
                .Include(b => b.Reviews)!
                .ThenInclude(r => r.SubComments)
                .Where(b => b.Id == id)
                .Select(b => new BookDto
                {
                    Book = b,
                    AvgRating = b.Reviews!.Average(r => r.Rating),
                    RatingCount = b.Reviews!.Count(r => r.Rating != null),
                    ReviewCount = b.Reviews!.Count(r => r.ParentCommentId == null)
                })
                .FirstOrDefaultAsync();



            if (book == null)
            {
                return NotFound();
            }
            else
            {
                book.Book.Reviews = book.Book.Reviews?.Where(r => r.ParentCommentId == null).ToList();
                BookDto = book;
            }
            return Page();
        }


    }
}

WebApp/Pages/Books/Index.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Books
{
    public class IndexModel : PageModel
    {
        private readonly DAL.EF.AppDbContext _context;

        public IndexModel(DAL.EF.AppDbContext context)
        {
            _context = context;
        }

        public IList<Book> Book { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Book = await _context.Books
                .Include(b => b.Publisher).ToListAsync();
        }
    }
}

WebApp/Pages/Books/Details.cshtml
@page "{id}"
@model DetailsModel

@{
    ViewData["Title"] = "Details";
}

@{
    double avgRating = Model.BookDto.AvgRating ?? 0;
    int ratingCount = Model.BookDto.RatingCount ?? 0;
    int reviewCount = Model.BookDto.ReviewCount ?? 0;
}


<style>

.sticky-nav{
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    z-index: 1030;
}



   .sticky-image-container {
   margin-top: 66px;
        position: sticky;
       top: 76px;
        z-index: 100; 
    }
    
    .scrollable-col{
    margin-top: 66px;
    }
    
    .book_title {
        font-size: 2.8rem;

    }

    .author_title {
        font-size: 1.5rem;

    }

    .custom-col {
        width: 224px;

    }

    a.title {
        color: inherit;
        text-decoration: none;
    }

    .avg {
        font-size: 1.25em;
        font-weight: 500;
    }


    .dt_head {
        font-size: 14px;
        font-weight: 400;

    }

    .dd_col {
        font-size: 14px;
        font-weight: 400;
        color: #4f4f4d;
    }

    .reviews {
        margin-top: 90px;
        margin-bottom: 5px;
    }

    .main_comment {
        border: 1px solid #5c636a;
        border-radius: 20px;
        padding: 20px;
        width: 700px;
    }

    .sub_comment {
        border: 1px solid #ffc107;
        border-radius: 20px;
        padding: 20px;

        margin-left: 100px;

    }

    .reply {
        border: 1px solid #ffc107;
        border-radius: 20px;
        padding: 20px;


    }

    .btno {
        border: 1px solid #5c636a;
        border-radius: 20px;
        margin-top: 10px;
    }
</style>


<div class="row overflow: hidden">
    <div class="custom-col mt-2">
        <div class="sticky-image-container">
            @if (!string.IsNullOrWhiteSpace(Model.BookDto.Book.ImageUrl))
            {
                <a asp-page="/Books/Details" asp-route-id="@Model.BookDto.Book.Id">
                    <img src="@Model.BookDto.Book.ImageUrl" alt="Book Image" width="200" />
                </a>
            }
        </div>
    </div>
    <div class="col scrollable-col" style="padding-left: 40px;">
        <div class="col-md-8">
            <div class="row h-25">
                <h5 class="d-block">
                    <a class="title book_title" asp-page="/Books/Details" asp-route-id="@Model.BookDto.Book.Id">
                        @Html.DisplayFor(modelItem => Model.BookDto.Book.Title)
                    </a>

                </h5>
                <div class="d-block author_title">
                    @foreach (var author in Model.BookDto.Book.BookAuthors!)
                    {
                        <a asp-page="/Index" asp-route-Search="@author.Author!.FirstName @author.Author.LastName"
                            asp-route-InAuthor="true" style="color: inherit;">
                            <span>
                                @Html.DisplayFor(modelItem => author.Author!.FirstName) @Html.DisplayFor(modelItem =>
                            author.Author!.LastName)
                            </span>
                        </a>
                    }
                </div>

                <div class="row rating" style="font-size: 26px;">
                    <div class="col-auto">
                        @for (int i = 1; i <= 5; i++)
                        {
                            <span class="@(i <= avgRating ? "fa fa-star" : "fa fa-star-o")"
                                style="color: @(i <= avgRating ? "#e87400" : "#8e8e97");">
                            </span>
                        }

                        <span class="avg">@avgRating.ToString("0.0")</span>
                    </div>
                    <div class="col-auto" style="padding-left: 0;">
                        <span class="dd_col">@ratingCount ratings · @reviewCount reviews</span>
                    </div>
                </div>
            </div>
            <div class="row align-items-center mt-2">
                <div class="col-md-12">

                    <span> @Html.DisplayFor(modelItem => Model.BookDto.Book.Summary)</span>

                </div>
            </div>
            <div class="row align-items-center mt-2">

                <div class="col-auto">
                    <span class="text-muted dt_head">Genres</span>
                </div>


                @foreach (var category in @Model.BookDto.Book.BookCategories!)
                {
                    <div class="col-auto" style="padding-left: 0;">
                        <a asp-page="/Index" asp-route-Search="@category.Category!.Name" asp-route-InGenre="true"
                            style="color: inherit;">
                            @Html.DisplayFor(modelItem => category.Category!.Name)
                        </a>
                    </div>
                }

            </div>

            <dl class="row mt-4">

                <h6 class="text mb-4">This edition</h6>

                <dt class="col-sm-2 dt_head text-muted">
                    Published
                </dt>
                <dd class="col-sm-10 dd_col">
                    Published @Html.DisplayFor(model => model.BookDto.Book.PublicationYear) by @Html.DisplayFor(model =>
                    model.BookDto.Book.Publisher!.Name)
                </dd>

                <dt class="col-sm-2 dt_head text-muted">
                    @Html.DisplayNameFor(model => model.BookDto.Book.ISBN)
                </dt>
                <dd class="col-sm-10 dd_col">
                    @Html.DisplayFor(model => model.BookDto.Book.ISBN)
                </dd>

                <dt class="col-sm-2 dt_head text-muted">
                    @Html.DisplayNameFor(model => model.BookDto.Book.Language)
                </dt>
                <dd class="col-sm-10 dd_col">
                    @Html.DisplayFor(model => model.BookDto.Book.Language)
                </dd>


            </dl>

            <form method="post" asp-page-handler="AddReview" id="addReviewForm">



                <div class="row reviews">
                    <div asp-validation-summary="ModelOnly" class="text-danger "></div>
                    <div class="col col-auto d-flex text-center align-items-center">
                        <h6 class="text">My rating:</h6>
                    </div>
                    <div class="col col-auto text-center" style="font-size: 26px;">
                        <span id="star1" class="fa fa-star-o" style="color: #8e8e97;" onclick="highlightStars(1)">
                        </span>
                        <span id="star2" class="fa fa-star-o" style="color: #8e8e97;" onclick="highlightStars(2)">
                        </span>
                        <span id="star3" class="fa fa-star-o" style="color: #8e8e97;" onclick="highlightStars(3)">
                        </span>
                        <span id="star4" class="fa fa-star-o" style="color: #8e8e97;" onclick="highlightStars(4)">
                        </span>
                        <span id="star5" class="fa fa-star-o" style="color: #8e8e97;" onclick="highlightStars(5)">
                        </span>
                    </div>
                </div>
                <div class="form-group">

                    <input type="hidden" asp-for="@Model.ReviewRating" id="ReviewRating" />

                    <textarea class="form-control main_comment" rows="4" asp-for="ReviewComment"
                        placeholder="Enter your review"></textarea>
                    <span asp-validation-for="@Model.ReviewComment" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="@Model.BookId" value="@Model.BookDto.Book.Id" />
                <div class="form-group">

                    <button class="btn btn-default btno" type="submit">
                        <i class="fa fa-comments-o"></i> Comment
                    </button>
                </div>
            </form>

            @if (Model.BookDto.Book.Reviews?.Count > 0)
            {
                <div class="revi">
                    <h6 class="text mt-5">Community Reviews</h6>
                    @foreach (var review in Model.BookDto.Book.Reviews!.OrderByDescending(sc => sc.CreatedAtDt))

                    {
                        <div class="cont mt-4 mb-5">


                            <div class="main_comment">
                                <div class="row mt-2">
                                    <div class="col">
                                        <div class="rating">
                                            @for (int i = 1; i <= 5; i++)
                                            {
                                                <span class="@(i <= review.Rating ? "fa fa-star" : "fa fa-star-o")"
                                                    style="color: @(i <= review.Rating ? "#e87400" : "#8e8e97");">
                                                </span>
                                            }


                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <span class="text dd_col">@review.CreatedAtDt</span>
                                    </div>

                                </div>


                                <div class="row mt-3">
                                    <div class="col col-md-12">
                                        <span class="text">@review.Comment</span>
                                    </div>
                                </div>

                            </div>

                            <div class="row mt-3">
                                <div class="col col-md-5">
                                    <form method="post" asp-page-handler="AddReply">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <textarea class="form-control  reply" rows="1" asp-for="ReviewComment"
                                                    style="border-color: #5c636a; padding: 10px" placeholder="Reply"></textarea>


                                                <button class="btn btn-default btno" style="margin-top: 0;" type="submit">
                                                    <i class="fa fa-comments-o"></i> Reply
                                                </button>

                                            </div>
                                            <span asp-validation-for="@Model.ReviewComment" class="text-danger"></span>
                                        </div>

                                        <input type="hidden" asp-for="@Model.BookId" value="@Model.BookDto.Book.Id" />
                                        <input type="hidden" asp-for="@Model.ReviewId" value="@review.Id" />
                                    </form>
                                </div>

                                <div class="col col-md-7 mb-2">
                                    @if (review.SubComments?.Any() == true)
                                    {
                                        @foreach (var subComment in review.SubComments.OrderByDescending(sc => sc.CreatedAtDt))
                                        {
                                            <div class="sub_comment mb-2 d-flex justify-content-between">
                                                <span class="text" style="text-align: start">@subComment.Comment</span>
                                                <span class="text dd_col" style="text-align: end">@subComment.CreatedAtDt</span>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>


                        </div>
                    }
                </div>
            }


        </div>
    </div>
</div>


<script>
    let reviewRating = 0;
    function highlightStars(rating) {


        reviewRating = rating;


        if ((document.getElementById(`star${5}`).className === "fa fa-star" && rating === 5) || (document.getElementById(`star${rating}`).className === "fa fa-star" && document.getElementById(`star${rating + 1}`).className === "fa fa-star-o")) {
            for (let i = 1; i <= 5; i++) {
                document.getElementById(`star${i}`).className = "fa fa-star-o";
                document.getElementById(`star${i}`).style.color = "#8e8e97";

            }

        }
        else {

            for (let i = 1; i <= 5; i++) {
                if (i <= rating) {
                    document.getElementById(`star${i}`).className = "fa fa-star";
                    document.getElementById(`star${i}`).style.color = "#e87400";
                }
                else {

                    document.getElementById(`star${i}`).className = "fa fa-star-o";
                    document.getElementById(`star${i}`).style.color = "#8e8e97";
                }
            }

        }
    }

    document.getElementById("addReviewForm").addEventListener("submit", function () {
        document.getElementById("ReviewRating").value = reviewRating;
    });
</script>